### ISSUE TITLE
2. Asymmetric Cryptography

### ISSUE THREAD

**Issue by yoseplee** [lecture4u/web-klein-schwarze-box#16]
# Assymetric Cryptography
this is related to security>asymmetric cryptography of the legacy program(KleinSchwarzeBox)

**Comment by yoseplee** [comment]
@JEONGCHAEEUN USE GITHUB ISSUE PLEASE!
you have to log your activities in this comment. I found that you've created issue and written some controller. but I don't understand you're not mentioning what you did.

**Comment by yoseplee** [comment]
Again, this is team play. your duty is let teammates know your current work, and address what you did so that colleague can recognize what to do next without wasting much time.

**Comment by jjj-netizen** [comment]
When I commit , should I write about what I do like this comment? Sorry I didn't know..
I just thought that is commit message's role.

**Comment by yoseplee** [comment]
commit message is for logging. I know it's similar.
but we're now use Github Issue. why we use this project management tool?
it prevents from scattering problems during the development, and make it clear what is the problem to solve or not.

it helps us gathering related information which prevents collective memory loss so that we can handle or resolve a problem issue by issue, which is much clear and effective.

I'm sorry that I hadn't explained those kind of concept enough to you. Let's learn what is project, collaboration through this project step by step. I'll do my best.

**Comment by yoseplee** [comment]
by the way, I'm modifying keyService class so that we can instantiate a KeyService with public and private key from the web application.

those work can be shown below.

[Web] -> public/private key -> [Api Server]: KeyService(pubKey, PriKey) -> encryption/decryption

**Comment by yoseplee** [comment]
# Error state
publicKey.getEncoded -> mapping -> X509EncodedKeySpec(publicKey.getEncoded())
this is true but there was an issue with getting key from REST and instantiate KeyService instance.
error was invalid key format.
possibly wrong character copied or missed when encoded key is thrown on the rest environment.

by the way, there are some arguments that must be mapped below.
``` java
byte[] keySpec = key.getPublicKey.getEncoded() //byte[]
//map with
X509EncodedKeySpec(keySpec)
```
see commit b85f64e0a88ce0ddef7df1ffaa0adc6f59f330c6

**Comment by yoseplee** [comment]
Therefore, newly written method 'makeKey' has no problem.
there is problem on communicating by Rest API, where I'm working on.

**Comment by yoseplee** [comment]
Finally grasp error point!
and I finally killed all the mosquitos in my room. yeah!

byte[] keySpec :-> no problem
byte[] keySpec -> REST(conv. to String) -> byte[] keySpec(<- Actually String -> byte[]) :-> Problem

there must be a problem on casting a encoded key into String and vice versa.
```err
Exception in thread "main" java.lang.IllegalArgumentException: Illegal base64 character 5b
	at java.base/java.util.Base64$Decoder.decode0(Base64.java:714)
	at java.base/java.util.Base64$Decoder.decode(Base64.java:526)
	at qtest.main.main(main.java:56)
```

## solving
1. base64 encoding and decoding is essential
2. as RESTful is based on String data type, use encodeToString(byte[]) instead of encode(byte[]). there a problem must arise as converting byte[] to string is automatically done when that data is thrown on response, and it is not safely converted in Base64 type.

but there still is error, which is Illegal base64 character 20 error.
this possibly arise during the copy and paste, where can be OS or computer specific problem.
therefore this work have to be with front development. keep calm.

**Comment by jjj-netizen** [comment]
I made hashPlusHashGenerate and deAndHashing function.
And I wonder there is an annotation to get value of key to decrypt digested data. 
or I should just put the digested value with key to decrypt.

Also I am trying to transaction part with some trouble with Pane class that only use on javaFx.

**Comment by jjj-netizen** [comment]
added signatureDe function
but that function is to decrypt, too. 
So if there is an annotation, this function could be modified.
keep going...,,.,
I will write issues more frequently..!!!!!!

**Comment by jjj-netizen** [comment]
Tabs of security and hash's codes structure are finished in my style.
I think all the other parts related with 'uicomponent' are constructed in javafx.
so it needs to write another way...I think..in my shallow knowledge..

**Comment by jjj-netizen** [comment]
# Testing ApiController.java screenshot with postman

## Public & Private Key
### apiGenerateKey() -  localhost:3000/api/genkey
![image](https://user-images.githubusercontent.com/32332719/58169290-581cd280-7ccb-11e9-9555-fa1ed3140215.png)

### publicEncryption() -  localhost:3000/api/puben
![image](https://user-images.githubusercontent.com/32332719/58169300-5c48f000-7ccb-11e9-9b80-dd8925ac41a3.png)

### publicDecryption() - localhost:3000/api/pubde
![image](https://user-images.githubusercontent.com/32332719/58169307-5f43e080-7ccb-11e9-953b-b27359cf1208.png)

### privateEncryption() - localhost:3000/api/prien
![image](https://user-images.githubusercontent.com/32332719/58169336-7a165500-7ccb-11e9-8db5-9b1aa7650982.png)

### privateDecryption() - localhost:3000/api/pride
![image](https://user-images.githubusercontent.com/32332719/58169344-7d114580-7ccb-11e9-9ae8-ecaee90395c7.png)

## Security check using key
### deAndHashing() - localhost:3000/api/datahash
![image](https://user-images.githubusercontent.com/32332719/58169610-23f5e180-7ccc-11e9-8fd0-d85f2c37cad2.png)

### signatureDe() - localhost:3000/api/signde
![image](https://user-images.githubusercontent.com/32332719/58169617-26f0d200-7ccc-11e9-8a10-5a1a0e965bce.png)
->using this encrypted private key, input signatureDe() as key of value.
![image](https://user-images.githubusercontent.com/32332719/58169629-2c4e1c80-7ccc-11e9-9ba0-e787a41f2c63.png)

+ Below a screenshot is about Hashing part, but I wrote the function on this issue.
## hash + hash hashing 
### hashPlusHashGenerate() - localhost:3000/api/hashplus
![image](https://user-images.githubusercontent.com/32332719/58169996-391f4000-7ccd-11e9-86d6-4eb79654148d.png)

**Comment by yoseplee** [comment]
Good!! I love this style

**Comment by yoseplee** [comment]
by the way, # I just finished asymmetric cryptography part
as you told me that you're working on annotating, please ``` git pull ``` 
and after finishing your work, please note me!
we have a chance to experience the Pull Request process
