### ISSUE TITLE
3. Digital Signature

### ISSUE THREAD

**Issue by yoseplee** [lecture4u/web-klein-schwarze-box#17]
# Digital Signature
this is related to security>security check using key of the legacy program(KleinSchwarzeBox)

this part is highly required to be discussed, as its UX is terrible, I think.
no one can grasp how to handle this program for experiencing digital signature.

**Comment by jjj-netizen** [comment]
I wrote code about signature private key part in branch issue-#16.
It's my fault, haha

**Comment by yoseplee** [comment]
# want to change UX/UI
I really hate this part of UX/UI of the legacy program. So I really wanted to improve this point.
I need your opinion. I hope that we can discuss this point in the next morning(23, Thur)

**Comment by yoseplee** [comment]
![image](https://user-images.githubusercontent.com/29854277/58175937-3710ad80-7cdc-11e9-8f93-308b27ce4238.png)

the point that I hate is its meaningless layout. most of users are get confused when they faced with this part. It's 구제불능, 최악.

@JEONGCHAEEUN  Hope you have a idea for improvement

**Comment by yoseplee** [comment]
# Prototype

![image](https://user-images.githubusercontent.com/29854277/58243814-5d8e2180-7d8c-11e9-91ad-051be62f2d4a.png)

legacy digital signature part was totally disaster.
It has not been addressed what digital signature is. because it only compares document. as meaning of digital signature, hash code must be added.

Plus, it's UX/UI(actually, UX) also very bad as a user cannot get their next action in the program.
Thus, in this prototype, it added hash function during the logic and improves UX

**Comment by yoseplee** [comment]
finish implementing this issue. so I close
