### ISSUE TITLE
Writing your first controller

### ISSUE THREAD

**Issue by yoseplee** [lecture4u/web-klein-schwarze-box#21]
# quest
For @JEONGCHAEEUN 

As ChaeEun has finished sequence diagram represents hashing, now we can write a controller that related. 

## Results should be...
1. Print on localhost:3000/api/hash
2. Success key and boolean value must be included into json format which is for returning value. Here’s example for you below

{“success”: true, “data”: “023ab8e9327”}

## tips for you
1. You have to instantiate a string data for your implementation. Ex. “123toHash”
2. You may have to crawl some code from legacy controller.
3. You must import some classes from package named ‘core’. 

#### you have enough ability to do this. Cheer up!
Please slack or comment at anytime you have a question. Good luck!

**Comment by jjj-netizen** [comment]
# Source code
![스크린샷 2019-05-13 오후 6 53 08](https://user-images.githubusercontent.com/32332719/57612935-ba315580-75b0-11e9-8ec1-11993f20d556.png)
* I imported /core/security for class 'Hash.java' on 'ApiController.java
* For setting localhost:3000/api/hash, I wrote it with annotation GetMapping
* Return type is Json.


# Result
![스크린샷 2019-05-13 오후 6 55 34](https://user-images.githubusercontent.com/32332719/57612950-bef60980-75b0-11e9-8b6a-241eac013616.png)
* Result screenshot on localhost:3000/api/hash 
* "data" is a name of key, and the value of that key is a hashed data which is generated by 'generatHashfunction()'.

**Comment by jjj-netizen** [comment]
With sequence diagram that I draw before, I can write simple controller, now!

**Comment by yoseplee** [comment]
Keep it going. So good.
