### ISSUE TITLE
4. Nonce Hashing expression

### ISSUE THREAD

**Issue by jjj-netizen** [lecture4u/web-klein-schwarze-box#24]
# Nonce Hashing function
![image](https://user-images.githubusercontent.com/32332719/58157988-76c39f00-7cb4-11e9-8d1d-2a70c0842c70.png)

* When user input data and nonce, then print nonce+data and hashed nonce+data. 
* It expressed by lambda expression on SampleController.java and also included in initialize function which made because of javaFx.
* So it needs to be made a function itself.

**Comment by jjj-netizen** [comment]
## nonce + data hashing test on postman

![image](https://user-images.githubusercontent.com/32332719/58161571-74b10e80-7cbb-11e9-9cde-b78cfe47888b.png)

**Comment by yoseplee** [comment]
I'll take care of this issue from right now

**Comment by yoseplee** [comment]
finish implementing this issue.
sorry for push to master branch instead of issue-24. It's my mistake

see commits below
0158d852da9b9a66a9e083d98c97a02753c9d72d
e7f5b68d7eefe5dc312cb66542de9c88188c9d38
504e820f27a03c898b727dda2b31498f8f015dc4
